"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$username\
[](fg:mauve bg:maroon)\
$directory\
[](fg:maroon bg:green)\
$git_branch\
$git_status\
[](fg:green bg:sapphire)\
$aws\
${custom.bash}\
$c\
${custom.cpp}\
$cobol\
$crystal\
$dart\
$elixir\
$elm\
$fennel\
${custom.fortran}\
$golang\
$guix_shell\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$meson\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$rlang\
$rust\
$scala\
$swift\
$zig\
[](fg:sapphire bg:text)\
$conda\
$docker_context\
[](fg:text bg:surface1)\
$time\
[ ](fg:surface1)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:base bg:mauve"

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = ""
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Illumos = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "fg:base bg:mauve"
style_root = "fg:red bg:mauve"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:maroon"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documenti" = "󰈙 "
"Scaricati" = " "
"Musica" = "󰝚 "
"Immagini" = " "
"Coding" = "󰲋 "
"Applicazioni" = " "
"Video" = " "
"Modelli" = " "
"Pubblici" = "󰀄"
Scrivania = "󰟀 "
#"~" = " "

[aws]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[custom.bash]
detect_extensions = ['sh', 'bash']
disabled = false
symbol =" "
style = "bg:sapphire"
format = '[[ $symbol( $output) ](fg:base bg:sapphire)]($style)'

[buf]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[c]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[custom.cpp]
command = 'echo v$(g++ --version | head -n1 | cut -d" " -f3)'
detect_extensions = ['cpp', 'hpp']
disabled = false
symbol =" "
style = "bg:sapphire"
format = '[[ $symbol( $output) ](fg:base bg:sapphire)]($style)'

[cobol]
symbol = "󱛟 "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[crystal]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[dart]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[elixir]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[elm]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[fennel]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[custom.fortran]
command = 'echo v$(gfortran --version | head -n1 | cut -d" " -f4)'
detect_extensions = ['f90']
disabled = false
symbol = "󱈚"
style = "bg:sapphire"
format = '[[ $symbol( $output) ](fg:base bg:sapphire)]($style)'

[golang]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[guix_shell]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[haxe]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[julia]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[kotlin]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[meson]
symbol = "󰔷 "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[nim]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[ocaml]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[perl]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[php]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[python]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[rlang]
symbol = "󰟔 "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[scala]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[swift]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[zig]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:text"
format = '[[ $symbol( $context) ](fg:base bg:text)]($style)'

[conda]
symbol = " "
style = "bg:text"
format = '[[ $symbol( $environment) ](fg:base bg:text)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface1"
format = '[[  $time ](fg:text bg:surface1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
