import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
	#"~/.config/alacritty/solarized-dark.toml"
]

[window]
opacity = 0.95

dimensions.columns = 150
dimensions.lines = 40

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Source Code Pro"
bold.family = "Source Code Pro"
italic.family = "Source Code Pro"
bold_italic.family = "Source Code Pro"

size = 11
