
[window]
opacity = 0.95

dimensions.columns = 150
dimensions.lines = 40

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "SauceCodePro Nerd Font"
bold.family = "SauceCodePro Nerd Font"
italic.family = "SauceCodePro Nerd Font"
bold_italic.family = "SauceCodePro Nerd Font"

size = 11.25

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
	#"~/.config/alacritty/solarized-dark.toml"
]
